import { useState, useEffect } from 'react';
import { X, Loader2, Save } from 'lucide-react';
import { useRoadmapCategories } from '@/hooks/use-roadmap-categories';
import type { CourseDTO, CreateCourseInput, UpdateCourseInput } from '@/services/admin-courses';

interface CourseFormModalProps {
    isOpen: boolean;
    onClose: () => void;
    onSubmit: (data: CreateCourseInput | UpdateCourseInput) => Promise<void>;
    initialData?: CourseDTO | null;
    isSubmitting?: boolean;
}

export default function CourseFormModal({
    isOpen,
    onClose,
    onSubmit,
    initialData,
    isSubmitting = false
}: CourseFormModalProps) {
    const { categories } = useRoadmapCategories();

    const [formData, setFormData] = useState<Omit<CreateCourseInput, 'slug'>>({
        title: '',
        description: '',
        category: '',
        type: 'intensive',
        icon: '',
        order_index: 0,
        is_published: false,
    });

    useEffect(() => {
        if (initialData) {
            setFormData({
                title: initialData.title,
                description: initialData.description || '',
                category: initialData.category || '',
                type: initialData.type,
                icon: initialData.icon || '',
                order_index: initialData.order_index,
                is_published: initialData.is_published,
            });
        } else {
            setFormData({
                title: '',
                description: '',
                category: '',
                type: 'intensive',
                icon: '',
                order_index: 0,
                is_published: false,
            });
        }
    }, [initialData, isOpen]);

    if (!isOpen) return null;

    const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
        const { name, value } = e.target;
        if (name === 'order_index') {
            setFormData(prev => ({ ...prev, order_index: parseInt(value) || 0 }));
        } else {
            setFormData(prev => ({ ...prev, [name]: value }));
        }
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        // Slug is auto-generated by the service layer — no need to include it
        await onSubmit(initialData ? { ...formData, id: initialData.id } : formData as CreateCourseInput);
    };

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm">
            <div className="w-full max-w-2xl bg-slate-900 border border-slate-800 rounded-xl shadow-2xl overflow-hidden">
                <div className="flex items-center justify-between p-6 border-b border-slate-800">
                    <h2 className="text-xl font-bold text-white">
                        {initialData ? 'Edit Course' : 'Add New Course'}
                    </h2>
                    <button onClick={onClose} className="p-2 text-slate-400 hover:text-white rounded-lg hover:bg-slate-800 transition-colors">
                        <X className="w-5 h-5" />
                    </button>
                </div>

                <form onSubmit={handleSubmit} className="p-6 space-y-6">
                    {/* Title */}
                    <div className="space-y-2">
                        <label className="text-sm font-medium text-slate-400">Title *</label>
                        <input
                            name="title"
                            value={formData.title}
                            onChange={handleChange}
                            className="w-full bg-slate-950 border border-slate-800 rounded-lg px-4 py-2.5 text-white focus:ring-2 focus:ring-blue-500/50 focus:border-blue-500 outline-none transition-all"
                            required
                        />
                    </div>

                    {/* Type + Category row */}
                    <div className="grid grid-cols-2 gap-6">
                        <div className="space-y-2">
                            <label className="text-sm font-medium text-slate-400">Type *</label>
                            <select
                                name="type"
                                value={formData.type}
                                onChange={handleChange}
                                className="w-full bg-slate-950 border border-slate-800 rounded-lg px-4 py-2.5 text-white focus:ring-2 focus:ring-blue-500/50 focus:border-blue-500 outline-none transition-all"
                            >
                                <option value="intensive">Intensive</option>
                                <option value="roadmap">Roadmap</option>
                            </select>
                        </div>
                        <div className="space-y-2">
                            <label className="text-sm font-medium text-slate-400">Category</label>
                            <select
                                name="category"
                                value={formData.category || ''}
                                onChange={handleChange}
                                className="w-full bg-slate-950 border border-slate-800 rounded-lg px-4 py-2.5 text-white focus:ring-2 focus:ring-blue-500/50 focus:border-blue-500 outline-none transition-all"
                            >
                                <option value="">— No Category —</option>
                                {categories.map(cat => (
                                    <option key={cat.id} value={cat.title}>{cat.icon ? `${cat.icon} ` : ''}{cat.title}</option>
                                ))}
                            </select>
                        </div>
                    </div>

                    {/* Description */}
                    <div className="space-y-2">
                        <label className="text-sm font-medium text-slate-400">Description</label>
                        <textarea
                            name="description"
                            value={formData.description || ''}
                            onChange={handleChange}
                            rows={3}
                            placeholder="Short course description..."
                            className="w-full bg-slate-950 border border-slate-800 rounded-lg px-4 py-2.5 text-white focus:ring-2 focus:ring-blue-500/50 focus:border-blue-500 outline-none transition-all resize-none"
                        />
                    </div>

                    {/* Icon + Order row */}
                    <div className="grid grid-cols-2 gap-6">
                        <div className="space-y-2">
                            <label className="text-sm font-medium text-slate-400">Icon (emoji or name)</label>
                            <input
                                name="icon"
                                value={formData.icon || ''}
                                onChange={handleChange}
                                placeholder="📚 or book"
                                className="w-full bg-slate-950 border border-slate-800 rounded-lg px-4 py-2.5 text-white focus:ring-2 focus:ring-blue-500/50 focus:border-blue-500 outline-none transition-all"
                            />
                        </div>
                        <div className="space-y-2">
                            <label className="text-sm font-medium text-slate-400">Order Index</label>
                            <input
                                name="order_index"
                                type="number"
                                value={formData.order_index}
                                onChange={handleChange}
                                className="w-full bg-slate-950 border border-slate-800 rounded-lg px-4 py-2.5 text-white focus:ring-2 focus:ring-blue-500/50 focus:border-blue-500 outline-none transition-all"
                            />
                        </div>
                    </div>

                    {/* Footer: Publish toggle + buttons */}
                    <div className="flex items-center justify-between pt-4 border-t border-slate-800">
                        <label className="flex items-center gap-3 cursor-pointer">
                            <div
                                className={`w-12 h-6 rounded-full p-1 transition-colors ${formData.is_published ? 'bg-blue-600' : 'bg-slate-700'}`}
                                onClick={() => setFormData(prev => ({ ...prev, is_published: !prev.is_published }))}
                            >
                                <div className={`w-4 h-4 rounded-full bg-white transform transition-transform ${formData.is_published ? 'translate-x-6' : 'translate-x-0'}`} />
                            </div>
                            <span className="text-sm font-medium text-slate-300">
                                {formData.is_published ? 'Published' : 'Draft'}
                            </span>
                        </label>

                        <div className="flex items-center gap-3">
                            <button type="button" onClick={onClose} className="px-4 py-2 text-slate-400 hover:text-white font-medium hover:bg-slate-800 rounded-lg transition-colors">
                                Cancel
                            </button>
                            <button
                                type="submit"
                                disabled={isSubmitting}
                                className="px-6 py-2 bg-blue-600 hover:bg-blue-500 text-white font-medium rounded-lg shadow-lg shadow-blue-900/20 flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed transition-all"
                            >
                                {isSubmitting ? <Loader2 className="w-4 h-4 animate-spin" /> : <Save className="w-4 h-4" />}
                                {initialData ? 'Update Course' : 'Create Course'}
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    );
}
