import { useState, useEffect } from 'react';
import { X, Loader2, Save } from 'lucide-react';
import { useRoadmapCategories } from '@/hooks/use-roadmap-categories';
import type { CourseDTO, CreateCourseInput, UpdateCourseInput } from '@/services/admin-courses';

interface CourseFormModalProps {
    isOpen: boolean;
    onClose: () => void;
    onSubmit: (data: CreateCourseInput | UpdateCourseInput) => Promise<void>;
    initialData?: CourseDTO | null;
    isSubmitting?: boolean;
}

export default function CourseFormModal({
    isOpen,
    onClose,
    onSubmit,
    initialData,
    isSubmitting = false
}: CourseFormModalProps) {
    const { categories } = useRoadmapCategories();

    const [formData, setFormData] = useState<Omit<CreateCourseInput, 'slug'>>({
        title: '',
        description: '',
        category: '',
        type: 'intensive',
        icon: '',
        order_index: 0,
        is_published: false,
    });

    useEffect(() => {
        if (initialData) {
            setFormData({
                title: initialData.title,
                description: initialData.description || '',
                category: initialData.category || '',
                type: initialData.type,
                icon: initialData.icon || '',
                order_index: initialData.order_index,
                is_published: initialData.is_published,
            });
        } else {
            setFormData({
                title: '',
                description: '',
                category: '',
                type: 'intensive',
                icon: '',
                order_index: 0,
                is_published: false,
            });
        }
    }, [initialData, isOpen]);

    if (!isOpen) return null;

    const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
        const { name, value } = e.target;
        if (name === 'order_index') {
            setFormData(prev => ({ ...prev, order_index: parseInt(value) || 0 }));
        } else {
            setFormData(prev => ({ ...prev, [name]: value }));
        }
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        // Slug is auto-generated by the service layer — no need to include it
        await onSubmit(initialData ? { ...formData, id: initialData.id } : formData as CreateCourseInput);
    };

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm">
            <div className="w-full max-w-2xl bg-[var(--bg-card)] border border-[var(--border-main)] rounded-xl shadow-2xl overflow-hidden animate-in zoom-in-95 duration-200">
                <div className="flex items-center justify-between p-6 border-b border-[var(--border-main)] bg-[var(--bg-muted)]/30">
                    <h2 className="text-xl font-bold text-[var(--text-main)]">
                        {initialData ? 'Edit Course' : 'Add New Course'}
                    </h2>
                    <button onClick={onClose} className="p-2 text-[var(--text-muted)] hover:text-[var(--text-main)] rounded-lg hover:bg-[var(--bg-muted)] transition-colors">
                        <X className="w-5 h-5" />
                    </button>
                </div>

                <form onSubmit={handleSubmit} className="p-6 space-y-6">
                    {/* Title */}
                    <div className="space-y-2">
                        <label className="text-sm font-medium text-[var(--text-secondary)]">Title *</label>
                        <input
                            name="title"
                            value={formData.title}
                            onChange={handleChange}
                            className="w-full bg-[var(--bg-muted)] border border-[var(--border-main)] rounded-lg px-4 py-2.5 text-[var(--text-main)] focus:ring-2 focus:ring-[var(--accent-primary)]/50 focus:border-[var(--accent-primary)] outline-none transition-all font-bold"
                            required
                        />
                    </div>

                    {/* Type + Category row */}
                    <div className="grid grid-cols-2 gap-6">
                        <div className="space-y-2">
                            <label className="text-sm font-medium text-[var(--text-secondary)]">Type *</label>
                            <select
                                name="type"
                                value={formData.type}
                                onChange={handleChange}
                                className="w-full bg-[var(--bg-muted)] border border-[var(--border-main)] rounded-lg px-4 py-2.5 text-[var(--text-main)] focus:ring-2 focus:ring-[var(--accent-primary)]/50 focus:border-[var(--accent-primary)] outline-none transition-all appearance-none font-bold"
                            >
                                <option value="intensive">Intensive</option>
                                <option value="roadmap">Roadmap</option>
                            </select>
                        </div>
                        <div className="space-y-2">
                            <label className="text-sm font-medium text-[var(--text-secondary)]">Category</label>
                            <select
                                name="category"
                                value={formData.category || ''}
                                onChange={handleChange}
                                className="w-full bg-[var(--bg-muted)] border border-[var(--border-main)] rounded-lg px-4 py-2.5 text-[var(--text-main)] focus:ring-2 focus:ring-[var(--accent-primary)]/50 focus:border-[var(--accent-primary)] outline-none transition-all appearance-none font-bold"
                            >
                                <option value="">— No Category —</option>
                                {categories.map(cat => (
                                    <option key={cat.id} value={cat.title}>{cat.icon ? `${cat.icon} ` : ''}{cat.title}</option>
                                ))}
                            </select>
                        </div>
                    </div>

                    {/* Description */}
                    <div className="space-y-2">
                        <label className="text-sm font-medium text-[var(--text-secondary)]">Description</label>
                        <textarea
                            name="description"
                            value={formData.description || ''}
                            onChange={handleChange}
                            rows={3}
                            placeholder="Short course description..."
                            className="w-full bg-[var(--bg-muted)] border border-[var(--border-main)] rounded-lg px-4 py-2.5 text-[var(--text-main)] focus:ring-2 focus:ring-[var(--accent-primary)]/50 focus:border-[var(--accent-primary)] outline-none transition-all resize-none placeholder-[var(--text-muted)]"
                        />
                    </div>

                    {/* Icon + Order row */}
                    <div className="grid grid-cols-2 gap-6">
                        <div className="space-y-2">
                            <label className="text-sm font-medium text-[var(--text-secondary)]">Icon (emoji or name)</label>
                            <input
                                name="icon"
                                value={formData.icon || ''}
                                onChange={handleChange}
                                placeholder="📚 or book"
                                className="w-full bg-[var(--bg-muted)] border border-[var(--border-main)] rounded-lg px-4 py-2.5 text-[var(--text-main)] focus:ring-2 focus:ring-[var(--accent-primary)]/50 focus:border-[var(--accent-primary)] outline-none transition-all font-bold placeholder-[var(--text-muted)]"
                            />
                        </div>
                        <div className="space-y-2">
                            <label className="text-sm font-medium text-[var(--text-secondary)]">Order Index</label>
                            <input
                                name="order_index"
                                type="number"
                                value={formData.order_index}
                                onChange={handleChange}
                                className="w-full bg-[var(--bg-muted)] border border-[var(--border-main)] rounded-lg px-4 py-2.5 text-[var(--text-main)] focus:ring-2 focus:ring-[var(--accent-primary)]/50 focus:border-[var(--accent-primary)] outline-none transition-all font-bold"
                            />
                        </div>
                    </div>

                    {/* Footer: Publish toggle + buttons */}
                    <div className="flex items-center justify-between pt-6 border-t border-[var(--border-main)]">
                        <label className="flex items-center gap-3 cursor-pointer group">
                            <div
                                className={`w-12 h-6 rounded-full p-1 transition-colors ${formData.is_published ? 'bg-[var(--accent-primary)]' : 'bg-[var(--border-main)]'}`}
                                onClick={() => setFormData(prev => ({ ...prev, is_published: !prev.is_published }))}
                            >
                                <div className={`w-4 h-4 rounded-full bg-white transform transition-transform ${formData.is_published ? 'translate-x-6' : 'translate-x-0'} shadow-sm`} />
                            </div>
                            <span className="text-sm font-bold text-[var(--text-main)] group-hover:text-[var(--accent-primary)] transition-colors">
                                {formData.is_published ? 'Published' : 'Draft'}
                            </span>
                        </label>

                        <div className="flex items-center gap-3">
                            <button type="button" onClick={onClose} className="px-4 py-2 text-[var(--text-muted)] hover:text-[var(--text-main)] font-bold hover:bg-[var(--bg-muted)] rounded-lg transition-colors">
                                Cancel
                            </button>
                            <button
                                type="submit"
                                disabled={isSubmitting}
                                className="px-6 py-2.5 bg-[var(--accent-primary)] hover:opacity-90 text-white font-bold rounded-lg shadow-lg shadow-[var(--accent-primary)]/20 flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed transition-all active:scale-95"
                            >
                                {isSubmitting ? <Loader2 className="w-4 h-4 animate-spin" /> : <Save className="w-4 h-4" />}
                                {initialData ? 'Update Course' : 'Create Course'}
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    );
}
